// <auto-generated />
using System;
using Maternidad.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Maternidad.Migrations
{
    [DbContext(typeof(MaternidadContext))]
    [Migration("20260506181550_SeedDataUtc")]
    partial class SeedDataUtc
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Maternidad.Dominio.AlertaNeonatal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaGenerada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RecienNacidoId")
                        .HasColumnType("integer");

                    b.Property<string>("TipoAlerta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TipoSignoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RecienNacidoId");

                    b.HasIndex("TipoSignoId");

                    b.ToTable("AlertaNeonatal");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Saturación de oxígeno por debajo del rango normal",
                            FechaGenerada = new DateTime(2024, 2, 20, 16, 5, 0, 0, DateTimeKind.Utc),
                            RecienNacidoId = 2,
                            TipoAlerta = "Moderada",
                            TipoSignoId = 3
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Saturación de oxígeno crítica, requiere intervención inmediata",
                            FechaGenerada = new DateTime(2024, 4, 5, 14, 5, 0, 0, DateTimeKind.Utc),
                            RecienNacidoId = 4,
                            TipoAlerta = "Critica",
                            TipoSignoId = 3
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Frecuencia respiratoria elevada",
                            FechaGenerada = new DateTime(2024, 4, 5, 14, 10, 0, 0, DateTimeKind.Utc),
                            RecienNacidoId = 4,
                            TipoAlerta = "Moderada",
                            TipoSignoId = 4
                        });
                });

            modelBuilder.Entity("Maternidad.Dominio.ComplicacionMaterna", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PartoId")
                        .HasColumnType("integer");

                    b.Property<string>("TipoComplicacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TratamientoAplicado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PartoId")
                        .IsUnique();

                    b.ToTable("ComplicacionMaterna");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Sangrado post cesárea moderado",
                            FechaRegistro = new DateTime(2024, 2, 20, 15, 0, 0, 0, DateTimeKind.Utc),
                            PartoId = 2,
                            TipoComplicacion = "Hemorragia",
                            TratamientoAplicado = "Oxitocina IV y compresión uterina"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Desgarro perineal grado 1",
                            FechaRegistro = new DateTime(2024, 5, 18, 8, 0, 0, 0, DateTimeKind.Utc),
                            PartoId = 5,
                            TipoComplicacion = "Desgarro",
                            TratamientoAplicado = "Sutura con anestesia local"
                        });
                });

            modelBuilder.Entity("Maternidad.Dominio.ComplicacionNeonatal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CIEmpleado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RecienNacidoId")
                        .HasColumnType("integer");

                    b.Property<string>("TipoComplicacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TratamientoAplicado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RecienNacidoId");

                    b.ToTable("ComplicacionNeonatal");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CIEmpleado = "2345678",
                            Descripcion = "Síndrome de dificultad respiratoria leve",
                            FechaRegistro = new DateTime(2024, 2, 20, 17, 0, 0, 0, DateTimeKind.Utc),
                            RecienNacidoId = 2,
                            TipoComplicacion = "Dificultad Respiratoria",
                            TratamientoAplicado = "Oxígeno suplementario por cánula nasal"
                        },
                        new
                        {
                            Id = 2,
                            CIEmpleado = "3456789",
                            Descripcion = "Niveles bajos de oxígeno en sangre",
                            FechaRegistro = new DateTime(2024, 4, 5, 14, 30, 0, 0, DateTimeKind.Utc),
                            RecienNacidoId = 4,
                            TipoComplicacion = "Hipoxia",
                            TratamientoAplicado = "Ventilación asistida y monitoreo continuo"
                        });
                });

            modelBuilder.Entity("Maternidad.Dominio.ControlPrenatal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CitaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaControl")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SeguimientoId")
                        .HasColumnType("integer");

                    b.Property<int>("SemanaGestacion")
                        .HasColumnType("integer");

                    b.Property<int>("TipoSignoPrenatalId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("SeguimientoId");

                    b.HasIndex("TipoSignoPrenatalId");

                    b.ToTable("ControlPrenatal");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CitaId = 101,
                            FechaControl = new DateTime(2023, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            SeguimientoId = 1,
                            SemanaGestacion = 12,
                            TipoSignoPrenatalId = 1,
                            Valor = 110m
                        },
                        new
                        {
                            Id = 2,
                            CitaId = 102,
                            FechaControl = new DateTime(2023, 9, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            SeguimientoId = 1,
                            SemanaGestacion = 24,
                            TipoSignoPrenatalId = 2,
                            Valor = 80m
                        },
                        new
                        {
                            Id = 3,
                            CitaId = 103,
                            FechaControl = new DateTime(2023, 11, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            SeguimientoId = 1,
                            SemanaGestacion = 36,
                            TipoSignoPrenatalId = 3,
                            Valor = 68m
                        },
                        new
                        {
                            Id = 4,
                            CitaId = 104,
                            FechaControl = new DateTime(2023, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            SeguimientoId = 2,
                            SemanaGestacion = 10,
                            TipoSignoPrenatalId = 1,
                            Valor = 115m
                        },
                        new
                        {
                            Id = 5,
                            CitaId = 105,
                            FechaControl = new DateTime(2023, 11, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            SeguimientoId = 2,
                            SemanaGestacion = 22,
                            TipoSignoPrenatalId = 4,
                            Valor = 28m
                        },
                        new
                        {
                            Id = 6,
                            CitaId = 106,
                            FechaControl = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            SeguimientoId = 3,
                            SemanaGestacion = 8,
                            TipoSignoPrenatalId = 5,
                            Valor = 90m
                        },
                        new
                        {
                            Id = 7,
                            CitaId = 107,
                            FechaControl = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            SeguimientoId = 3,
                            SemanaGestacion = 28,
                            TipoSignoPrenatalId = 1,
                            Valor = 120m
                        },
                        new
                        {
                            Id = 8,
                            CitaId = 108,
                            FechaControl = new DateTime(2023, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            SeguimientoId = 4,
                            SemanaGestacion = 14,
                            TipoSignoPrenatalId = 2,
                            Valor = 75m
                        },
                        new
                        {
                            Id = 9,
                            CitaId = 109,
                            FechaControl = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            SeguimientoId = 4,
                            SemanaGestacion = 32,
                            TipoSignoPrenatalId = 3,
                            Valor = 72m
                        },
                        new
                        {
                            Id = 10,
                            CitaId = 110,
                            FechaControl = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            SeguimientoId = 5,
                            SemanaGestacion = 10,
                            TipoSignoPrenatalId = 1,
                            Valor = 108m
                        });
                });

            modelBuilder.Entity("Maternidad.Dominio.EvaluacionInicial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ApgarMin1")
                        .HasColumnType("integer");

                    b.Property<int>("ApgarMin5")
                        .HasColumnType("integer");

                    b.Property<string>("CIEmpleado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaEvaluacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RecienNacidoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RecienNacidoId");

                    b.ToTable("EvaluacionInicial");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApgarMin1 = 8,
                            ApgarMin5 = 9,
                            CIEmpleado = "1234567",
                            FechaEvaluacion = new DateTime(2024, 1, 15, 8, 50, 0, 0, DateTimeKind.Utc),
                            RecienNacidoId = 1
                        },
                        new
                        {
                            Id = 2,
                            ApgarMin1 = 6,
                            ApgarMin5 = 7,
                            CIEmpleado = "2345678",
                            FechaEvaluacion = new DateTime(2024, 2, 20, 14, 35, 0, 0, DateTimeKind.Utc),
                            RecienNacidoId = 2
                        },
                        new
                        {
                            Id = 3,
                            ApgarMin1 = 9,
                            ApgarMin5 = 10,
                            CIEmpleado = "1234567",
                            FechaEvaluacion = new DateTime(2024, 3, 10, 22, 25, 0, 0, DateTimeKind.Utc),
                            RecienNacidoId = 3
                        },
                        new
                        {
                            Id = 4,
                            ApgarMin1 = 5,
                            ApgarMin5 = 6,
                            CIEmpleado = "3456789",
                            FechaEvaluacion = new DateTime(2024, 4, 5, 12, 5, 0, 0, DateTimeKind.Utc),
                            RecienNacidoId = 4
                        },
                        new
                        {
                            Id = 5,
                            ApgarMin1 = 8,
                            ApgarMin5 = 9,
                            CIEmpleado = "2345678",
                            FechaEvaluacion = new DateTime(2024, 5, 18, 7, 15, 0, 0, DateTimeKind.Utc),
                            RecienNacidoId = 5
                        });
                });

            modelBuilder.Entity("Maternidad.Dominio.Parto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Anestesia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CIEmpleado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CIPaciente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Complicaciones")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoParto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Parto");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Anestesia = "Epidural",
                            CIEmpleado = "1234567",
                            CIPaciente = "7654321",
                            Complicaciones = "Ninguna",
                            FechaHora = new DateTime(2024, 1, 15, 8, 30, 0, 0, DateTimeKind.Utc),
                            Observaciones = "Parto sin complicaciones",
                            TipoParto = "Natural"
                        },
                        new
                        {
                            Id = 2,
                            Anestesia = "General",
                            CIEmpleado = "2345678",
                            CIPaciente = "8765432",
                            Complicaciones = "Sangrado leve",
                            FechaHora = new DateTime(2024, 2, 20, 14, 0, 0, 0, DateTimeKind.Utc),
                            Observaciones = "Se requirió cesárea de emergencia",
                            TipoParto = "Cesárea"
                        },
                        new
                        {
                            Id = 3,
                            Anestesia = "Ninguna",
                            CIEmpleado = "1234567",
                            CIPaciente = "9876543",
                            Complicaciones = "Ninguna",
                            FechaHora = new DateTime(2024, 3, 10, 22, 15, 0, 0, DateTimeKind.Utc),
                            Observaciones = "Parto rápido sin intervención",
                            TipoParto = "Natural"
                        },
                        new
                        {
                            Id = 4,
                            Anestesia = "Epidural",
                            CIEmpleado = "3456789",
                            CIPaciente = "6543210",
                            Complicaciones = "Ninguna",
                            FechaHora = new DateTime(2024, 4, 5, 11, 45, 0, 0, DateTimeKind.Utc),
                            Observaciones = "Cesárea programada",
                            TipoParto = "Cesárea"
                        },
                        new
                        {
                            Id = 5,
                            Anestesia = "Epidural",
                            CIEmpleado = "2345678",
                            CIPaciente = "5432109",
                            Complicaciones = "Desgarro leve",
                            FechaHora = new DateTime(2024, 5, 18, 7, 0, 0, 0, DateTimeKind.Utc),
                            Observaciones = "Se realizó episiotomía",
                            TipoParto = "Natural"
                        });
                });

            modelBuilder.Entity("Maternidad.Dominio.RecienNacido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CIPaciente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaHoraNacimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PartoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PesoGramos")
                        .HasColumnType("numeric");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TallaCm")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("PartoId")
                        .IsUnique();

                    b.ToTable("RecienNacido");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CIPaciente = "7654321",
                            Estado = "Sano",
                            FechaHoraNacimiento = new DateTime(2024, 1, 15, 8, 45, 0, 0, DateTimeKind.Utc),
                            Nombre = "Bebé García",
                            PartoId = 1,
                            PesoGramos = 3200m,
                            Sexo = "Masculino",
                            TallaCm = 50m
                        },
                        new
                        {
                            Id = 2,
                            CIPaciente = "8765432",
                            Estado = "En observación",
                            FechaHoraNacimiento = new DateTime(2024, 2, 20, 14, 30, 0, 0, DateTimeKind.Utc),
                            Nombre = "Bebé Mamani",
                            PartoId = 2,
                            PesoGramos = 2900m,
                            Sexo = "Femenino",
                            TallaCm = 48m
                        },
                        new
                        {
                            Id = 3,
                            CIPaciente = "9876543",
                            Estado = "Sano",
                            FechaHoraNacimiento = new DateTime(2024, 3, 10, 22, 20, 0, 0, DateTimeKind.Utc),
                            Nombre = "Bebé Flores",
                            PartoId = 3,
                            PesoGramos = 3500m,
                            Sexo = "Masculino",
                            TallaCm = 52m
                        },
                        new
                        {
                            Id = 4,
                            CIPaciente = "6543210",
                            Estado = "En observación",
                            FechaHoraNacimiento = new DateTime(2024, 4, 5, 12, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Bebé Quispe",
                            PartoId = 4,
                            PesoGramos = 2750m,
                            Sexo = "Femenino",
                            TallaCm = 47m
                        },
                        new
                        {
                            Id = 5,
                            CIPaciente = "5432109",
                            Estado = "Sano",
                            FechaHoraNacimiento = new DateTime(2024, 5, 18, 7, 10, 0, 0, DateTimeKind.Utc),
                            Nombre = "Bebé Chávez",
                            PartoId = 5,
                            PesoGramos = 3800m,
                            Sexo = "Masculino",
                            TallaCm = 54m
                        });
                });

            modelBuilder.Entity("Maternidad.Dominio.SeguimientoPrenatal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CIEmpleado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CIPaciente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("PartoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PartoId");

                    b.ToTable("SeguimientoPrenatal");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CIEmpleado = "1234567",
                            CIPaciente = "7654321",
                            Estado = "Completado",
                            FechaInicio = new DateTime(2023, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PartoId = 1
                        },
                        new
                        {
                            Id = 2,
                            CIEmpleado = "2345678",
                            CIPaciente = "8765432",
                            Estado = "Completado",
                            FechaInicio = new DateTime(2023, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            PartoId = 2
                        },
                        new
                        {
                            Id = 3,
                            CIEmpleado = "1234567",
                            CIPaciente = "9876543",
                            Estado = "Completado",
                            FechaInicio = new DateTime(2023, 8, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            PartoId = 3
                        },
                        new
                        {
                            Id = 4,
                            CIEmpleado = "3456789",
                            CIPaciente = "6543210",
                            Estado = "Completado",
                            FechaInicio = new DateTime(2023, 9, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            PartoId = 4
                        },
                        new
                        {
                            Id = 5,
                            CIEmpleado = "2345678",
                            CIPaciente = "5432109",
                            Estado = "Completado",
                            FechaInicio = new DateTime(2023, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PartoId = 5
                        });
                });

            modelBuilder.Entity("Maternidad.Dominio.SignoVitalNeonatal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CIEmpleado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RecienNacidoId")
                        .HasColumnType("integer");

                    b.Property<int>("TipoSignoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("RecienNacidoId");

                    b.HasIndex("TipoSignoId");

                    b.ToTable("SignoVitalNeonatal");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CIEmpleado = "1234567",
                            FechaHora = new DateTime(2024, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            RecienNacidoId = 1,
                            TipoSignoId = 1,
                            Valor = 145m
                        },
                        new
                        {
                            Id = 2,
                            CIEmpleado = "1234567",
                            FechaHora = new DateTime(2024, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            RecienNacidoId = 1,
                            TipoSignoId = 2,
                            Valor = 37.0m
                        },
                        new
                        {
                            Id = 3,
                            CIEmpleado = "2345678",
                            FechaHora = new DateTime(2024, 2, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            RecienNacidoId = 2,
                            TipoSignoId = 3,
                            Valor = 93m
                        },
                        new
                        {
                            Id = 4,
                            CIEmpleado = "2345678",
                            FechaHora = new DateTime(2024, 2, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            RecienNacidoId = 2,
                            TipoSignoId = 1,
                            Valor = 155m
                        },
                        new
                        {
                            Id = 5,
                            CIEmpleado = "1234567",
                            FechaHora = new DateTime(2024, 3, 10, 23, 0, 0, 0, DateTimeKind.Utc),
                            RecienNacidoId = 3,
                            TipoSignoId = 2,
                            Valor = 36.8m
                        },
                        new
                        {
                            Id = 6,
                            CIEmpleado = "3456789",
                            FechaHora = new DateTime(2024, 4, 5, 14, 0, 0, 0, DateTimeKind.Utc),
                            RecienNacidoId = 4,
                            TipoSignoId = 3,
                            Valor = 92m
                        },
                        new
                        {
                            Id = 7,
                            CIEmpleado = "3456789",
                            FechaHora = new DateTime(2024, 4, 5, 14, 0, 0, 0, DateTimeKind.Utc),
                            RecienNacidoId = 4,
                            TipoSignoId = 4,
                            Valor = 65m
                        },
                        new
                        {
                            Id = 8,
                            CIEmpleado = "2345678",
                            FechaHora = new DateTime(2024, 5, 18, 9, 0, 0, 0, DateTimeKind.Utc),
                            RecienNacidoId = 5,
                            TipoSignoId = 1,
                            Valor = 138m
                        });
                });

            modelBuilder.Entity("Maternidad.Dominio.TipoSignoPrenatal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unidad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ValorMax")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ValorMin")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("TipoSignoPrenatal");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Presión Arterial Sistólica",
                            Unidad = "mmHg",
                            ValorMax = 140m,
                            ValorMin = 90m
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Frecuencia Cardíaca",
                            Unidad = "bpm",
                            ValorMax = 100m,
                            ValorMin = 60m
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Peso",
                            Unidad = "kg",
                            ValorMax = 120m,
                            ValorMin = 45m
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Altura Uterina",
                            Unidad = "cm",
                            ValorMax = 38m,
                            ValorMin = 20m
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Glucosa",
                            Unidad = "mg/dL",
                            ValorMax = 110m,
                            ValorMin = 70m
                        });
                });

            modelBuilder.Entity("Maternidad.Dominio.TipoSignoVitalNeonatal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unidad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ValorMax")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ValorMin")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("TipoSignoVitalNeonatal");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Frecuencia Cardíaca",
                            Unidad = "bpm",
                            ValorMax = 160m,
                            ValorMin = 100m
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Temperatura",
                            Unidad = "°C",
                            ValorMax = 37.5m,
                            ValorMin = 36.5m
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Saturación de Oxígeno",
                            Unidad = "%",
                            ValorMax = 100m,
                            ValorMin = 95m
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Frecuencia Respiratoria",
                            Unidad = "rpm",
                            ValorMax = 60m,
                            ValorMin = 30m
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Glucosa Neonatal",
                            Unidad = "mg/dL",
                            ValorMax = 125m,
                            ValorMin = 45m
                        });
                });

            modelBuilder.Entity("Maternidad.Dominio.TratamientoNeonatal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CIEmpleado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CodigoMedicamento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RecienNacidoId")
                        .HasColumnType("integer");

                    b.Property<string>("TipoTratamiento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RecienNacidoId");

                    b.ToTable("TratamientoNeonatal");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CIEmpleado = "2345678",
                            CodigoMedicamento = "MED-001",
                            Descripcion = "Oxígeno suplementario por cánula nasal al 30%",
                            FechaFin = new DateTime(2024, 2, 22, 10, 0, 0, 0, DateTimeKind.Utc),
                            FechaInicio = new DateTime(2024, 2, 20, 17, 0, 0, 0, DateTimeKind.Utc),
                            RecienNacidoId = 2,
                            TipoTratamiento = "Respiratorio"
                        },
                        new
                        {
                            Id = 2,
                            CIEmpleado = "3456789",
                            CodigoMedicamento = "MED-002",
                            Descripcion = "Ventilación mecánica asistida",
                            FechaInicio = new DateTime(2024, 4, 5, 14, 30, 0, 0, DateTimeKind.Utc),
                            RecienNacidoId = 4,
                            TipoTratamiento = "Ventilación"
                        },
                        new
                        {
                            Id = 3,
                            CIEmpleado = "1234567",
                            CodigoMedicamento = "MED-003",
                            Descripcion = "Vitamina K profiláctica",
                            FechaFin = new DateTime(2024, 1, 15, 9, 30, 0, 0, DateTimeKind.Utc),
                            FechaInicio = new DateTime(2024, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            RecienNacidoId = 1,
                            TipoTratamiento = "Vitamínico"
                        },
                        new
                        {
                            Id = 4,
                            CIEmpleado = "1234567",
                            CodigoMedicamento = "MED-003",
                            Descripcion = "Vitamina K profiláctica",
                            FechaFin = new DateTime(2024, 3, 10, 23, 0, 0, 0, DateTimeKind.Utc),
                            FechaInicio = new DateTime(2024, 3, 10, 22, 30, 0, 0, DateTimeKind.Utc),
                            RecienNacidoId = 3,
                            TipoTratamiento = "Vitamínico"
                        },
                        new
                        {
                            Id = 5,
                            CIEmpleado = "2345678",
                            CodigoMedicamento = "MED-003",
                            Descripcion = "Vitamina K profiláctica",
                            FechaFin = new DateTime(2024, 5, 18, 8, 0, 0, 0, DateTimeKind.Utc),
                            FechaInicio = new DateTime(2024, 5, 18, 7, 30, 0, 0, DateTimeKind.Utc),
                            RecienNacidoId = 5,
                            TipoTratamiento = "Vitamínico"
                        });
                });

            modelBuilder.Entity("Maternidad.Dominio.AlertaNeonatal", b =>
                {
                    b.HasOne("Maternidad.Dominio.RecienNacido", "RecienNacido")
                        .WithMany("Alertas")
                        .HasForeignKey("RecienNacidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Maternidad.Dominio.TipoSignoVitalNeonatal", "TipoSigno")
                        .WithMany()
                        .HasForeignKey("TipoSignoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecienNacido");

                    b.Navigation("TipoSigno");
                });

            modelBuilder.Entity("Maternidad.Dominio.ComplicacionMaterna", b =>
                {
                    b.HasOne("Maternidad.Dominio.Parto", "Parto")
                        .WithOne("ComplicacionMaterna")
                        .HasForeignKey("Maternidad.Dominio.ComplicacionMaterna", "PartoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parto");
                });

            modelBuilder.Entity("Maternidad.Dominio.ComplicacionNeonatal", b =>
                {
                    b.HasOne("Maternidad.Dominio.RecienNacido", "RecienNacido")
                        .WithMany("Complicaciones")
                        .HasForeignKey("RecienNacidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecienNacido");
                });

            modelBuilder.Entity("Maternidad.Dominio.ControlPrenatal", b =>
                {
                    b.HasOne("Maternidad.Dominio.SeguimientoPrenatal", "Seguimiento")
                        .WithMany("Controles")
                        .HasForeignKey("SeguimientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Maternidad.Dominio.TipoSignoPrenatal", "TipoSigno")
                        .WithMany("Controles")
                        .HasForeignKey("TipoSignoPrenatalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Seguimiento");

                    b.Navigation("TipoSigno");
                });

            modelBuilder.Entity("Maternidad.Dominio.EvaluacionInicial", b =>
                {
                    b.HasOne("Maternidad.Dominio.RecienNacido", "RecienNacido")
                        .WithMany()
                        .HasForeignKey("RecienNacidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecienNacido");
                });

            modelBuilder.Entity("Maternidad.Dominio.RecienNacido", b =>
                {
                    b.HasOne("Maternidad.Dominio.Parto", "Parto")
                        .WithOne("RecienNacido")
                        .HasForeignKey("Maternidad.Dominio.RecienNacido", "PartoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parto");
                });

            modelBuilder.Entity("Maternidad.Dominio.SeguimientoPrenatal", b =>
                {
                    b.HasOne("Maternidad.Dominio.Parto", "Parto")
                        .WithMany("SeguimientosPrenatal")
                        .HasForeignKey("PartoId");

                    b.Navigation("Parto");
                });

            modelBuilder.Entity("Maternidad.Dominio.SignoVitalNeonatal", b =>
                {
                    b.HasOne("Maternidad.Dominio.RecienNacido", "RecienNacido")
                        .WithMany("SignosVitales")
                        .HasForeignKey("RecienNacidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Maternidad.Dominio.TipoSignoVitalNeonatal", "TipoSigno")
                        .WithMany("Signos")
                        .HasForeignKey("TipoSignoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecienNacido");

                    b.Navigation("TipoSigno");
                });

            modelBuilder.Entity("Maternidad.Dominio.TratamientoNeonatal", b =>
                {
                    b.HasOne("Maternidad.Dominio.RecienNacido", "RecienNacido")
                        .WithMany("Tratamientos")
                        .HasForeignKey("RecienNacidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecienNacido");
                });

            modelBuilder.Entity("Maternidad.Dominio.Parto", b =>
                {
                    b.Navigation("ComplicacionMaterna")
                        .IsRequired();

                    b.Navigation("RecienNacido")
                        .IsRequired();

                    b.Navigation("SeguimientosPrenatal");
                });

            modelBuilder.Entity("Maternidad.Dominio.RecienNacido", b =>
                {
                    b.Navigation("Alertas");

                    b.Navigation("Complicaciones");

                    b.Navigation("SignosVitales");

                    b.Navigation("Tratamientos");
                });

            modelBuilder.Entity("Maternidad.Dominio.SeguimientoPrenatal", b =>
                {
                    b.Navigation("Controles");
                });

            modelBuilder.Entity("Maternidad.Dominio.TipoSignoPrenatal", b =>
                {
                    b.Navigation("Controles");
                });

            modelBuilder.Entity("Maternidad.Dominio.TipoSignoVitalNeonatal", b =>
                {
                    b.Navigation("Signos");
                });
#pragma warning restore 612, 618
        }
    }
}
