// <auto-generated />
using System;
using Maternidad.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Maternidad.Migrations
{
    [DbContext(typeof(MaternidadContext))]
    [Migration("20260506010749_m1")]
    partial class m1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Maternidad.Dominio.AlertaNeonatal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaGenerada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RecienNacidoId")
                        .HasColumnType("integer");

                    b.Property<string>("TipoAlerta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TipoSignoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RecienNacidoId");

                    b.HasIndex("TipoSignoId");

                    b.ToTable("AlertaNeonatal");
                });

            modelBuilder.Entity("Maternidad.Dominio.ComplicacionMaterna", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PartoId")
                        .HasColumnType("integer");

                    b.Property<string>("TipoComplicacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TratamientoAplicado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PartoId")
                        .IsUnique();

                    b.ToTable("ComplicacionMaterna");
                });

            modelBuilder.Entity("Maternidad.Dominio.ComplicacionNeonatal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CIEmpleado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RecienNacidoId")
                        .HasColumnType("integer");

                    b.Property<string>("TipoComplicacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TratamientoAplicado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RecienNacidoId");

                    b.ToTable("ComplicacionNeonatal");
                });

            modelBuilder.Entity("Maternidad.Dominio.ControlPrenatal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CitaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaControl")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SeguimientoId")
                        .HasColumnType("integer");

                    b.Property<int>("SemanaGestacion")
                        .HasColumnType("integer");

                    b.Property<int>("TipoSignoPrenatalId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("SeguimientoId");

                    b.HasIndex("TipoSignoPrenatalId");

                    b.ToTable("ControlPrenatal");
                });

            modelBuilder.Entity("Maternidad.Dominio.EvaluacionInicial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ApgarMin1")
                        .HasColumnType("integer");

                    b.Property<int>("ApgarMin5")
                        .HasColumnType("integer");

                    b.Property<string>("CIEmpleado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaEvaluacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RecienNacidoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RecienNacidoId");

                    b.ToTable("EvaluacionInicial");
                });

            modelBuilder.Entity("Maternidad.Dominio.Parto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Anestesia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CIEmpleado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CIPaciente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Complicaciones")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoParto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Parto");
                });

            modelBuilder.Entity("Maternidad.Dominio.RecienNacido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CIPaciente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaHoraNacimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PartoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PesoGramos")
                        .HasColumnType("numeric");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TallaCm")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("PartoId")
                        .IsUnique();

                    b.ToTable("RecienNacido");
                });

            modelBuilder.Entity("Maternidad.Dominio.SeguimientoPrenatal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CIEmpleado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CIPaciente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("PartoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PartoId");

                    b.ToTable("SeguimientoPrenatal");
                });

            modelBuilder.Entity("Maternidad.Dominio.SignoVitalNeonatal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CIEmpleado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RecienNacidoId")
                        .HasColumnType("integer");

                    b.Property<int>("TipoSignoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("RecienNacidoId");

                    b.HasIndex("TipoSignoId");

                    b.ToTable("SignoVitalNeonatal");
                });

            modelBuilder.Entity("Maternidad.Dominio.TipoSignoPrenatal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unidad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ValorMax")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ValorMin")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("TipoSignoPrenatal");
                });

            modelBuilder.Entity("Maternidad.Dominio.TipoSignoVitalNeonatal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unidad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ValorMax")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ValorMin")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("TipoSignoVitalNeonatal");
                });

            modelBuilder.Entity("Maternidad.Dominio.TratamientoNeonatal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CIEmpleado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CodigoMedicamento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RecienNacidoId")
                        .HasColumnType("integer");

                    b.Property<string>("TipoTratamiento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RecienNacidoId");

                    b.ToTable("TratamientoNeonatal");
                });

            modelBuilder.Entity("Maternidad.Dominio.AlertaNeonatal", b =>
                {
                    b.HasOne("Maternidad.Dominio.RecienNacido", "RecienNacido")
                        .WithMany("Alertas")
                        .HasForeignKey("RecienNacidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Maternidad.Dominio.TipoSignoVitalNeonatal", "TipoSigno")
                        .WithMany()
                        .HasForeignKey("TipoSignoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecienNacido");

                    b.Navigation("TipoSigno");
                });

            modelBuilder.Entity("Maternidad.Dominio.ComplicacionMaterna", b =>
                {
                    b.HasOne("Maternidad.Dominio.Parto", "Parto")
                        .WithOne("ComplicacionMaterna")
                        .HasForeignKey("Maternidad.Dominio.ComplicacionMaterna", "PartoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parto");
                });

            modelBuilder.Entity("Maternidad.Dominio.ComplicacionNeonatal", b =>
                {
                    b.HasOne("Maternidad.Dominio.RecienNacido", "RecienNacido")
                        .WithMany("Complicaciones")
                        .HasForeignKey("RecienNacidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecienNacido");
                });

            modelBuilder.Entity("Maternidad.Dominio.ControlPrenatal", b =>
                {
                    b.HasOne("Maternidad.Dominio.SeguimientoPrenatal", "Seguimiento")
                        .WithMany("Controles")
                        .HasForeignKey("SeguimientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Maternidad.Dominio.TipoSignoPrenatal", "TipoSigno")
                        .WithMany("Controles")
                        .HasForeignKey("TipoSignoPrenatalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Seguimiento");

                    b.Navigation("TipoSigno");
                });

            modelBuilder.Entity("Maternidad.Dominio.EvaluacionInicial", b =>
                {
                    b.HasOne("Maternidad.Dominio.RecienNacido", "RecienNacido")
                        .WithMany()
                        .HasForeignKey("RecienNacidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecienNacido");
                });

            modelBuilder.Entity("Maternidad.Dominio.RecienNacido", b =>
                {
                    b.HasOne("Maternidad.Dominio.Parto", "Parto")
                        .WithOne("RecienNacido")
                        .HasForeignKey("Maternidad.Dominio.RecienNacido", "PartoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parto");
                });

            modelBuilder.Entity("Maternidad.Dominio.SeguimientoPrenatal", b =>
                {
                    b.HasOne("Maternidad.Dominio.Parto", "Parto")
                        .WithMany("SeguimientosPrenatal")
                        .HasForeignKey("PartoId");

                    b.Navigation("Parto");
                });

            modelBuilder.Entity("Maternidad.Dominio.SignoVitalNeonatal", b =>
                {
                    b.HasOne("Maternidad.Dominio.RecienNacido", "RecienNacido")
                        .WithMany("SignosVitales")
                        .HasForeignKey("RecienNacidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Maternidad.Dominio.TipoSignoVitalNeonatal", "TipoSigno")
                        .WithMany("Signos")
                        .HasForeignKey("TipoSignoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecienNacido");

                    b.Navigation("TipoSigno");
                });

            modelBuilder.Entity("Maternidad.Dominio.TratamientoNeonatal", b =>
                {
                    b.HasOne("Maternidad.Dominio.RecienNacido", "RecienNacido")
                        .WithMany("Tratamientos")
                        .HasForeignKey("RecienNacidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecienNacido");
                });

            modelBuilder.Entity("Maternidad.Dominio.Parto", b =>
                {
                    b.Navigation("ComplicacionMaterna")
                        .IsRequired();

                    b.Navigation("RecienNacido")
                        .IsRequired();

                    b.Navigation("SeguimientosPrenatal");
                });

            modelBuilder.Entity("Maternidad.Dominio.RecienNacido", b =>
                {
                    b.Navigation("Alertas");

                    b.Navigation("Complicaciones");

                    b.Navigation("SignosVitales");

                    b.Navigation("Tratamientos");
                });

            modelBuilder.Entity("Maternidad.Dominio.SeguimientoPrenatal", b =>
                {
                    b.Navigation("Controles");
                });

            modelBuilder.Entity("Maternidad.Dominio.TipoSignoPrenatal", b =>
                {
                    b.Navigation("Controles");
                });

            modelBuilder.Entity("Maternidad.Dominio.TipoSignoVitalNeonatal", b =>
                {
                    b.Navigation("Signos");
                });
#pragma warning restore 612, 618
        }
    }
}
